config/routes.rb
Rails.application.routes.draw do
  root :to => "jobs#index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  resources :sessions
  resources :jobs
  resources :companies

  post '/invoices/create', to: 'invoices#create'
  post '/invoices/webhook', to: 'invoices#webhook'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/job.rb
class Job < ApplicationRecord
    validates :company, :company_logo, :title, :description, :website, :presence => true
    enum location_mode: [ :REMOTE, :ON_SITE, :HYBRID]
    has_one_attached :company_logo
    has_many :invoice
    # Uncomment if you use companies table
    # belongs_to :company1
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_request, only: %i[ edit update destroy]
  after_action :allow_iframe
  skip_before_action :verify_authenticity_token

  # GET /jobs or /jobs.json
  def index
    key = "%#{params[:key]}%"
    @jobs = Job.where("UPPER(title) LIKE UPPER(?) OR UPPER(description) LIKE UPPER(?)", key, key)
    @jobs = @jobs.filter {|j| j.published == true}
    @jobs.sort_by! {|j| - j.created_at.to_i}
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.invoice.clear
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :website, :company, :company_logo, :location, :location_mode, :salary, :category)
    end

    def authenticate_request
      redirect_to root_url unless User.current_user(session) || Job.find(params[:id]).published == false
    end

    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_card(job, full_size = nil)
    content_tag(:div, class: "card", style: "margin-bottom: 0.5%;" + (full_size ? 'transform: scale(1);' : '')) do
      content_tag(:div, class: "row g-0 align-items-center") do
        #***************************** Image *****************************
        content_tag(:div, class: "col-2 d-flex justify-content-center") do
          image_tag(job.company_logo, class: "logo-fluid")
        end +
        #***************************** Body ******************************
        content_tag(:div, class: "col-10") do
          content_tag(:div, class: "card-body preview-card") do
            #***************************** Title *************************
            content_tag(:h5, job.title, class: 'card-title') +
            #***************************** Subtitle **********************
            content_tag(:h6, job.company, class: 'card-subtitle mb-2 text-body-secondary') +
            #***************************** Secondary *********************
            content_tag(:p, class: 'card-text', style: 'line-height: 1;') do
              concat content_tag(:small, job.location, class: 'text-body-secondary')
              concat tag.br(class: 'small')
              concat content_tag(:small, job.location_mode, class: 'text-body-secondary')
            end +
            content_tag(:span, class: 'card-text', style: 'float: left;') do
              content_tag(:small, job.created_at, class: 'text-body-secondary')
            end +
            content_tag(:span, class: 'card-text', style: 'float: right;') do
              content_tag(:small, "$#{job.salary ? job.salary : "------"}", class: 'text-body-secondary')
            end
          end
        end
      end
    end
  end

  def back_to_jobs_button(small = nil)
    link_to jobs_path, class: "btn btn-dark" + (small ? ' btn-sm' : '') do
      content_tag(:i, "", class: "fa fa-solid fa-rotate-left") + " | Back to jobs"
    end
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mx-auto w-85 text-center">
    <%= form.label :company_name, class: "d-block tittle-position fuente-letras";%>
    <%= form.text_field :company, class: "form-control rounded border-dark" %>
  </div>

  <div>
    <%= form.label :company_logo, class: "d.d-block tittle-position fuente-letras" %>
    <%= form.file_field :company_logo, class: "fuente-letras" %>
  </div>

  <div class="mx-auto w-85 text-center">
    <%= form.label :location, class: "d-block tittle-position fuente-letras" %>
    <%= form.text_field :location, class: "form-control rounded border-dark" %>
  </div>

  <div class="mx-auto w-85 text-center">
    <%= form.label :location_mode, class: "d-block tittle-position fuente-letras" %>
    <%= form.select :location_mode, Job.location_modes.keys, {}, { class: "form-control rounden w-100 border-dark text-center" } %>
  </div>

  <div class="mx-auto w-85 text-center">
    <%= form.label :estimate_salary, class: "d-block tittle-position fuente-letras" %>
    <%= form.number_field :salary, class: "form-control rounded border-dark" %>
  </div>

  <div class="mx-auto w-85 text-center">
    <%= form.label :title, class: "d-block tittle-position fuente-letras" %>
    <%= form.text_field :title, class: "form-control rounded border-dark" %>
  </div>

  <div>
    <%= form.label :description, class:"d-block fuente-letras" %>
    <%= form.text_area :description, class: "field field-big" %>
  </div>

  <div class="mx-auto w-85 text-center">
    <%= form.label :job_website, class: "d-block tittle-position fuente-letras" %>
    <%= form.text_field :website, class: "form-control rounded border-dark" %>
  </div>
  <p><small>
    Applicants will be sent to the website you specify to apply for the position.
  </small></p>

<!----------------------------------------- Form submit buttom ------------------------------------------->
  <div class="container-fluid.fixed-bottom white">
    <div class="row">
      <div class="col-12 d-flex justify-content-center align-items-center" style="height: 10vh;">
        <%=
          if edit == true
            form.submit "Update", class: "btn btn-primary apply-buttom"
          else
            form.submit "Continue" , class: "btn btn-primary apply-buttom"
          end
        %>
      </div>
    </div>
  </div>

<% end %>

  

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= job.website %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= job.company %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= job.location %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job.salary %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= job.category %>
  </p>

</div>

app/views/jobs/edit.html.erb
<p></p>
<div class="d-flex" style="margin: 0 0 0 2%;">
  <%= link_to "Show this job", @job, class: "btn btn-dark btn-sm me-1"%>
  <%= back_to_jobs_button("small") %>
</div>

<!------------------------------------ Card  --------------------------------------->
<div class="card">
  <div class="row g-0 align-items-center">
    <!--------------------------  Body  -------------------------->
      <div class="card-body">
        <!-------------- Title  ---------------->
        <h2 class="card-title">Edit job</h2>
        <!-------------- Form  ---------------->
        <%= render "form", job: @job, edit: true %>

      </div>
  </div>
</div>

app/views/jobs/index.html.erb
<br>

<div id="jobs">
  <% @jobs.each do |job| %>
    <a href=<%=job_path(job)%> class="card-link">
      <%=job_card(job, "true")%>
    </a>
  <% end %>
</div>

app/views/jobs/new.html.erb
<p style="color: green"><%= notice %></p>

<%= back_to_jobs_button %>

<!------------------------------------ Card  --------------------------------------->
<div class="card">
  <div class="row g-0 align-items-center">
    <!--------------------------  Body  -------------------------->
      <div class="card-body">
        <!-------------- Title  ---------------->
        <h2 class="card-title">New job</h2>
        <!-------------- Form  ---------------->
        <%= render "form", job: @job, edit: false %>

      </div>
  </div>
</div>

app/views/jobs/show.html.erb
<p></p>
<div class="d-flex" style="margin: 0 0 1% 2%;">
    <!-------------------- Show Edit/Delete Job ----------------------->
    <% if current_user || @job.published == false %>
      <%= back_to_jobs_button("small") %>

      <%= link_to "Edit", edit_job_path(@job), class: "btn btn-dark btn-sm ms-1"%>
      <%= button_to "Destroy", @job, method: :delete , class: "btn btn-dark btn-sm ms-1"%>
    <% else %>
      <%= back_to_jobs_button %>
    <% end %>
</div>

<!---------------------------------------------------- Card -------------------------------------------------->
<div class="card show">
  <div class="card-body">
  <!------------------------------------ Publication Success Notification ------------------------------------>
    <% if params["success"] == 'true' %>
      <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Successful posting!</h4>
        Your job has been posted successfully. It will now appear on our job board for 8 weeks.
        <br> Thank you for using our job posting service
        <br> <a href="/jobs">Go to Job Board</a>
      </div>
    <% end %>

  <!------------------------------------ Payment Requeriment Notification ------------------------------------>

    <% if @job.published == false %>
      <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Hi there!</h4>
        This <strong>job has not been published yet</strong>. You can post it for <strong>5 USD</strong> using BTC or Lightning with the following link.
        <br>
        Remember that you can  <%= link_to "edit this job", edit_job_path(@job) %>  before publishing it.
        <hr>
        <!---------------------------------------- Publish Form ---------------------------------------------->
        <%= form_tag invoices_create_path, method: :post do %>
          <div class="mx-auto w-85 text-center">
            <%= label_tag :email, "Invoice Email *", class: "d-block tittle-position fuente-letras" %>
            <%= text_field_tag :email, nil, class: "form-control rounded border-dark" , required: true %>
          </div>

          <%= hidden_field_tag :job_id, @job.id %>
          <%= hidden_field_tag :company, @job.company %>

          <div class="row">
              <div class="col-12 d-flex justify-content-center align-items-center" style="height: 10vh;">
                <%= submit_tag "Publish Job", data: {turbo: "false"}, class: "btn btn-primary apply-buttom" %>
              </div>
            </div>
        <% end %>
      </div>

      <!------------------------------------------------ Card Preview ----------------------------------------->
      <h6 style="text-align: center;"> Board preview</h6>
      <%=job_card(@job, true)%>
      <br>

      <h6 style="text-align: center;"> Description preview </h5>
    <% end %>

  <!------------------------------------ Job Description ------------------------------------------------------>
  <div class="show-description">
    <h2 class="card-title"><%= @job.title %></h2>
      <p class="card-text" style="line-height: 1;">
        <small class="text-body-secondary"> <%= @job.company%> - <%= @job.location %> - <%= @job.location_mode %> </small>
      </p>
      <span class="card-text" style="float: left; ">
        <small class="text-body-secondary"><%= @job.created_at %></small>
      </span>
      <span class="card-text" style="float: right;">
        <small class="text-body-secondary"> $<%= @job.salary ? @job.salary : "------" %></small>
      </span>
    <br><br><br>
    <h5 class="card-title"> Job Description</h5>
    <p class="card-text", style="white-space: pre-wrap;"> <%= @job.description %></p>
    <br><br>
    </div>
  </div>
</div>


<!------------------------------------------ Apply Buttom ------------------------------------------------------->

<div class="container-fluid fixed-bottom white">
  <div class="row">
    <div class="col-12 d-flex justify-content-center align-items-center" style="height: 10vh;">
      <a href="<%=@job.website%>" target="_blank" class="btn btn-primary apply-buttom">Apply</a>
    </div>
  </div>
</div>