config/routes.rb
Rails.application.routes.draw do
  root :to => "jobs#index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  resources :sessions
  resources :jobs
  resources :companies

  post '/invoices/create', to: 'invoices#create'
  post '/invoices/webhook', to: 'invoices#webhook'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!------------------------------------- Boostrap CSS  ---------------------------------------->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <!------------------------------------- Awesome Icons  ---------------------------------------->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <!------------------------------------- Boostrap JS  ---------------------------------------->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

    <!------------------------------------- Admin Navgar ------------------------------------->

    <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", log_out_path %>
      <% end %>
    </div>
    <!--------------------------------- Navbar Search ----------------------------------->
    <nav class="navbar-search">
      <div class="container-fluid" style="padding: 20px 0;">
        <form class="d-flex" role="search">
          <input class="form-control search" type="search" id="search-input" placeholder="Search Job">
          <a href="<%=new_job_path%>" class="btn btn-outline-light">Post Job</a>
        </form>
      </div>
    </nav>

    <div class="row justify-content-center">
      <div class="col-xxl-7 col-xl-9 col-lg-10 col-md-11 col-sm-12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>


<!------------------------------------- Search Logic  ---------------------------------------->
<script>
  var searchInput = document.querySelector('#search-input');

  searchInput.addEventListener('keydown', (event) => {
    if (event.keyCode === 13) {
      var searchTerm = searchInput.value;
      var endpointUrl = `/jobs?key=${encodeURIComponent(searchTerm)}`;
      window.location.href = endpointUrl;
    }
  });
</script>